// Copyright (c) Strange Loop Games. All rights reserved.
// See LICENSE file in the project root for full license information.
// <auto-generated />

namespace Eco.Mods.TechTree
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;
    using Eco.Gameplay.Blocks;
    using Eco.Gameplay.Components;
    using Eco.Gameplay.DynamicValues;
    using Eco.Gameplay.Items;
    using Eco.Gameplay.Objects;
    using Eco.Gameplay.Players;
    using Eco.Gameplay.Skills;
    using Eco.Gameplay.Systems;
    using Eco.Gameplay.Systems.TextLinks;
    using Eco.Core.Items;
    using Eco.Shared.Localization;
    using Eco.Shared.Serialization;
    using Eco.Shared.Utils;
    using Eco.World;
    using Eco.World.Blocks;
    using Eco.Gameplay.Pipes;

    [RequiresSkill(typeof(MiningSkill), 7)]
    public partial class DirtDecompositionLv3Recipe :
        RecipeFamily
    {
        public DirtDecompositionLv3Recipe()
        {

            this.Recipes = new List<Recipe>
            {
                new Recipe(
                    "DirtDecompositionLv3",
                    Localizer.DoStr("Dirt Decomposition Lv3"),
                    new IngredientElement[]
                    {
                    new IngredientElement(typeof(DirtItem), 20, true),  
                    },
                    new CraftingElement[]
                    {
               new CraftingElement<ClayItem>(2),
               new CraftingElement<SandItem>(7),
               new CraftingElement<CompostItem>(1),					
                    }
                )
            };
            this.LaborInCalories = CreateLaborInCaloriesValue(800, typeof(MiningSkill)); 
            this.ExperienceOnCraft = 0.1f;  
            this.CraftMinutes = CreateCraftTimeValue(typeof(DirtDecompositionLv3Recipe), 2f, typeof(MiningSkill));     
            this.Initialize(Localizer.DoStr("Dirt Decomposition Lv3"), typeof(DirtDecompositionLv3Recipe));

            CraftingComponent.AddRecipe(typeof(SensorBasedBeltSorterObject), this);
        }
    }

}
